version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BROKER=your_broker_url
      - BACKEND=your_backend_url
    depends_on:
      - celery
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  celery:
    image: celery
    command: celery -A app worker --loglevel=info
    environment:
      - BROKER=your_broker_url
      - BACKEND=your_backend_url
